In [3]:
import numpy as np

In [4]:
np.__version__

'2.1.3'

In [5]:
print(np.__version__)

2.1.3


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.where(a > 5, a,0))

[[0 0 0]
 [0 0 6]
 [7 8 9]]


In [9]:
print(type(a))

<class 'numpy.ndarray'>
